[demo-crates]
crates = ["lazy_static"]
github-repos = []
local-crates = []

[sandbox]
memory-limit = "2G"
build-log-max-size = "2M"
build-log-max-lines = 1000

[server.acl]
allowed-users = []

[server.callback]
timeout-secs = 30
retry-count = 3
