[demo-crates]
crates = ["lazy_static"]
github-repos = []
local-crates = []

[sandbox]
memory-limit = { "GIGABYTES" = 2 }
build-log-max-size = { "MEGABYTES" = 2 }
build-log-max-lines = 1000

[server.acl]
allowed-users = []

[server.callback]
timeout-secs = 30
retry-count = 3
